// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[6];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
"\n\nEnum.proto\022\010Protocol*\250\001\n\006INGAME\022\016\n\nENT"
"ER_GAME\020\000\022\017\n\013CREATE_GAME\020\001\022\016\n\nGAME_START"
"\020\002\022\016\n\nLEAVE_GAME\020\003\022\014\n\010GAME_END\020\004\022\t\n\005SPAW"
"N\020\005\022\013\n\007DESPAWN\020\006\022\010\n\004MOVE\020\007\022\021\n\rPLAYER_ACT"
"ION\020\010\022\010\n\004CHAT\020\t\022\020\n\014PICK_UP_ITEM\020\n*T\n\010Mov"
"eType\022\r\n\tMOVE_NONE\020\000\022\r\n\tMOVE_IDLE\020\001\022\r\n\tM"
"OVE_WALK\020\002\022\014\n\010MOVE_RUN\020\003\022\r\n\tMOVE_JUMP\020\004*"
"d\n\nObjectType\022\017\n\013OBJECT_IDLE\020\000\022\021\n\rOBJECT"
"_PLAYER\020\001\022\016\n\nOBJECT_KEY\020\002\022\017\n\013OBJECT_DOOR"
"\020\003\022\021\n\rOBJECT_BUTTON\020\004*L\n\013StageNumber\022\016\n\n"
"STAGE_NULL\020\000\022\r\n\tSTAGE_ONE\020\001\022\r\n\tSTAGE_TWO"
"\020\002\022\017\n\013STAGE_THREE\020\003*)\n\nActionType\022\014\n\010LIG"
"HT_ON\020\000\022\r\n\tDOOR_OPEN\020\001*\032\n\017ClickedItemTyp"
"e\022\007\n\003KEY\020\000b\006proto3"
;
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 538, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
    return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* INGAME_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[0];
    }
    bool INGAME_IsValid(int value) {
        switch (value) {
        case 0:
        case 1:
        case 2:
        case 3:
        case 4:
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
            return true;
        default:
            return false;
        }
    }

    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveType_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[1];
    }
    bool MoveType_IsValid(int value) {
        switch (value) {
        case 0:
        case 1:
        case 2:
        case 3:
        case 4:
            return true;
        default:
            return false;
        }
    }

    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[2];
    }
    bool ObjectType_IsValid(int value) {
        switch (value) {
        case 0:
        case 1:
        case 2:
        case 3:
        case 4:
            return true;
        default:
            return false;
        }
    }

    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StageNumber_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[3];
    }
    bool StageNumber_IsValid(int value) {
        switch (value) {
        case 0:
        case 1:
        case 2:
        case 3:
            return true;
        default:
            return false;
        }
    }

    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionType_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[4];
    }
    bool ActionType_IsValid(int value) {
        switch (value) {
        case 0:
        case 1:
            return true;
        default:
            return false;
        }
    }

    const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClickedItemType_descriptor() {
        ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
        return file_level_enum_descriptors_Enum_2eproto[5];
    }
    bool ClickedItemType_IsValid(int value) {
        switch (value) {
        case 0:
            return true;
        default:
            return false;
        }
    }


    // @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
